### ISSUE TITLE
Underground villages not generating

### ISSUE THREAD

**Issue by srnyx** [TheGrimsey/Stoneholm#1]
**Describe the bug**
Getting a warning on startup that may be causing the villages to not generate
Warning: `[16:28:25] [main/WARN]: Reference map 'stoneholm-refmap.json' for stoneholm.mixins.json could not be read. If this is a development environment you can ignore this message`

**Mod version:** 1.0.1

**Fabric API version:** 0.32.5

**Minecraft version:** 1.16.5

**Additional Context:**
Doing `/locate` says it can't find any structures

**Comment by TheGrimsey** [comment]
Interesting. Stoneholm does not use any mixins. I'll remove the mixin JSON from the mod in the next hotfix.

_Looking at the fabric discord I see you say the world has been played a bit._ 
According to the [Minecraft wiki](https://minecraft.fandom.com/wiki/Commands/locate#Result), the ``/locate`` command only finds structures within 201x201 chunks of the user. (And we can't generate in structures in existing chunks)

Could you try teleporting 3000+ blocks out as well and using the command again?

**Comment by srnyx** [comment]
> Interesting. Stoneholm does not use any mixins. I definitely need to remove the mixin JSON from the mod in the next hotfix.
> 
> _Looking at the fabric discord I see you say the world has been played a bit._
> According to the [Minecraft wiki](https://minecraft.fandom.com/wiki/Commands/locate#Result), the `/locate` command only finds structures within 201x201 chunks of the user. (And we can't generate in structures in existing chunks)
> 
> Could you try teleporting 3000+ blocks out as well and using the command again?

Yeah I teleported to 10,000 10,000 and did it, still nothing. Then I went to 15,000 15,000 and still nothing.
_It didn't find any structures for **any** of the mods I added_

**Comment by TheGrimsey** [comment]
> It didn't find any structures for **any** of the mods I added

For any mod? That to me makes it sound like it's something else messing it up. 
What mods does your server have?

**Comment by srnyx** [comment]
> > It didn't find any structures for **any** of the mods I added
> 
> For any mod? That to me makes it sound like it's something else messing it up.
> What mods does your server have?

No, no. For any of the mods I **added along with Stonehelm**, of course, other mods I added **before** loading the world are generating structures.
But, one of the mods are generating structures fine in The End.

**Comment by TheGrimsey** [comment]
Okay so testing a bit. With Stoneholm, Deep Dungeons, and Dungeons of Exile:

Everything generates in a new world.
![](https://i.imgur.com/v8IClef.png)

Going into a world without any of the mods installed and then rejoining the world with them:
![](https://i.imgur.com/aD4qozL.png)

Doesn't seem like the error is between them.
I need more info to reproduce this issue.

**Comment by srnyx** [comment]
> Okay so testing a bit. With (lastest version of each) Stoneholm, Deep Dungeons, and Dungeons of Exile:
> 
> Everything generates in a new world.
> ![](https://camo.githubusercontent.com/fc191f735018cfd8cad33c535e361b0ee881f95912a28d715ddf50dd195ced58/68747470733a2f2f692e696d6775722e636f6d2f763849436c65662e706e67)
> 
> Going into a world without any of the mods installed and then rejoining the world with them:
> ![](https://camo.githubusercontent.com/a42815e1e11610b7212483fd72c4621b39cb04eac9c6558c9d7201d7d979757d/68747470733a2f2f692e696d6775722e636f6d2f614434716f7a4c2e706e67)
> 
> Doesn't seem like the error is between them.
> I need more info to reproduce this issue.

Maybe they **were** generating but where I was looking was just not places where they were. I'll try launching a single-player world to see if it's because of a mod incompatibility.

**Comment by srnyx** [comment]
> Maybe they **were** generating but where I was looking was just not places where they were. I'll try launching a single-player world to see if it's because of a mod incompatibility.

Alright, so, in my single-player world, all of them **do** generate.
In my server, though, only the World of Exile (Dungeons of Exile) dungeons are generating.
I went ahead and looked in `level.dat`. There was no structure item for Deep Dungeons or Stonehelm, which means they weren't like "injected" into `level.dat` (or something else, I have no clue).

**Comment by TheGrimsey** [comment]
> Alright, so, in my single-player world, all of them **do** generate.
> In my server, though, only the World of Exile (Dungeons of Exile) dungeons are generating.

Hmmm. Could you start a new world on the server (or copy the server files somewhere locally) and quickly check if ``/locate`` works then?

**Comment by srnyx** [comment]
> Hmmm. Could you start a new world on the server (or copy the server files somewhere locally) and quickly check if `/locate` works then?

Yep, it works. All of them generate.

> I went ahead and looked in `level.dat`. There was no structure item for Deep Dungeons or Stonehelm, which means they weren't like "injected" into `level.dat` (or something else, I have no clue), therefore causing them not to generate.

Scratch this. That was just the structure settings that were being saved.

**Comment by TheGrimsey** [comment]
Sorry, been out of town for about a week.

I am not sure what the issue is here. 
If it generates fine on a new world with the same set up it's something with the individual world. Still don't think I have enough information to solve this.

**Comment by srnyx** [comment]
> I am not sure what the issue is here.
> If it generates fine on a new world with the same set up it's something with the individual world. Still don't think I have enough information to solve this.

I just ran another test. I copied every single file from the server onto my computer and ran the server.
I found an underground village on my local server and copied the coordinates. I went back on the server and TPed to the coordinates and the terrain was completely different.

**Comment by srnyx** [comment]
@TheGrimsey @RDKRACZ
The structures only started generated at around 65k blocks out.
This is super strange as I don't think anyone has ever gone this far.
There seemed to be like new chunks being generated after a certain point (about 65k).
I think this may be because of [Gunpowder Teleport](https://www.curseforge.com/minecraft/mc-mods/gunpowder-teleport) and its/wild command, but it's highly unlikely.
