### ISSUE TITLE
 Failed to load structure nbt file from : minecraft:empty (caught with Blame)

### ISSUE THREAD

**Issue by colby-boucher** [TheGrimsey/Stoneholm#11]
I saw this error because Minecraft crashed a few minutes later, but I don't believe this was the cause of it. In any case I imagine this isn't intentional:

****************** Blame Report Structure NBT 1.17-4.2.0-fabric ******************

 Failed to load structure nbt file from : minecraft:empty
 The path represented by this is:  data/minecraft/structures/empty.nbt
 The calling Template Pool is: stoneholm:hallways/hallway_x
 Most common cause is that there is a typo in this path to the nbt file.
 Please let the mod author know about this so they can double check to make sure the path is correct.
 A common mistake is putting the structure nbt file in the asset folder when it needs to go in data/structures folder.

**Comment by TheGrimsey** [comment]
Should be unrelated. Blame doesn't recognize ``minecraft:empty`` as a structure since it's defined in code.

I have been trying to figure out why it pops up for this piece specifically though before but with no luck.
