### ISSUE TITLE
Crash when creating world with the new Fabric API

### ISSUE THREAD

**Issue by FirstMegaGame4** [TheGrimsey/Stoneholm#16]
**Describe the bug**
Crash when creating world

**To Reproduce**
Create a World

**Expected behavior**

**Mod version:**
1.4.1

**Fabric API version:**
0.46.3

**Minecraft version:**
1.18.1

Crash Report :
https://crashy.net/BSbnBHwon5QetERJl7y6?raw

**Comment by TheGrimsey** [comment]
This should be fixed in latest version.
