### ISSUE TITLE
water in the underground village corridors

### ISSUE THREAD

**Issue by egoiced** [TheGrimsey/Stoneholm#2]
there is a possibility cause this to happen,the underground villages conflicted with the lake/river/ocean.when world trying to generated the lake/ocean/river and the underground village it conflicted 

it's just annoying travelling the flowing water
![2021-04-14_17 38 44](https://user-images.githubusercontent.com/79297738/114701144-9d799b80-9d4c-11eb-8c83-4bda595dfa04.png)
![2021-04-14_17 38 58](https://user-images.githubusercontent.com/79297738/114701150-9f435f00-9d4c-11eb-91fa-4bde226cd6d3.png)

**Mod version:1.1.0**

**Fabric API version:0.29.3**

**Minecraft version:1.16.5+0.11.3 Fabric Loader**

**Comment by orznick14** [comment]
I am also having this problem, running BYG, Lakeside and River Redux.

**Comment by TheGrimsey** [comment]
I am uncertain how exactly to fix this but I have some ideas for the future.

**Comment by TheGrimsey** [comment]
Next update (**V1.3**) will finally solve this issue.
