### ISSUE TITLE
Crash on generating village

### ISSUE THREAD

**Issue by deadspidervenom** [TheGrimsey/Stoneholm#3]
**Describe the bug**
As i roam around the world, when it attempts to generate the unground village it instantly crashes.

**To Reproduce**
1. Go to Underground Village Village

**Expected behavior**
A village generates

**Mod version:**
1.2.0 (also did it on 1.1.0)

**Fabric API version:**
33.1

**Minecraft version:**
1.16.5

**Additional Context:**
Crash Log
https://pastebin.com/LJsg3Ur6

**Comment by TheGrimsey** [comment]
That is an interesting error. It appears like it is unable to generate the village because it there are no structure pieces in the pool.

**Comment by TheGrimsey** [comment]
Are you using a custom world type?

**Comment by deadspidervenom** [comment]
i have a custom world generator installed, but i am using the default generation, i do have mods that add too the generation.

**Comment by deadspidervenom** [comment]
After a bit of testing (had other issues to work on first) i figured out it seems to be a incompatibility with this mod

https://www.curseforge.com/minecraft/mc-mods/towelette

Which is strange cause i did not think it messed with generation.

**Comment by TheGrimsey** [comment]
That is odd.

I don't think there is much I can do to fix this then since Stoneholm doesn't do anything but generate structures, it doesn't make any changes to how the game handles waterlogging.

**Comment by deadspidervenom** [comment]
After looking at the error log, i looked up part of it and found this post, it might help. It is about a different area entirely, but the error is the same (though plug you mod and fabric in instead.)
https://stackoverflow.com/questions/32101688/illegalargumentexception-bound-must-be-positive

**Comment by TheGrimsey** [comment]
Yeah, I know exactly where the issue is happening. It's when picking the next structure piece to place out in Minecraft code.

Something is making the game not load the structure pools or somehow deleting them.

**Comment by deadspidervenom** [comment]
Hmm maybe yung (from yung's better _____)  could help? or maybe this mod dev
https://github.com/frqnny/mostructures

**Comment by RDKRACZ** [comment]
@deadspidervenom maybe try to run your mods with Blame? - https://www.curseforge.com/minecraft/mc-mods/blame-fabric - It should tell where the issue is.
I would ask TelepathicGrunt (https://github.com/TelepathicGrunt/RepurposedStructures-Fabric) because they always know what goes wrong with mods issues.

**Comment by deadspidervenom** [comment]
@RDKRACZ Ill give blame a try, and yea i have updated mods since the log was given no changes.

**Comment by deadspidervenom** [comment]
What i got

> ****************** Blame Report 1.16.4-2.4.1 ******************

 Empty template pool found from : stoneholm:start_pool
 The path represented by this is:  data/stoneholm/worldgen/template_pool/start_pool.json
 Most common cause is that there is a typo in this path to the template pool which then points to a non-existent pool.
 Please let the mod author know about this so they can double check the path to make sure it is correct.

**Comment by TheGrimsey** [comment]
> > ****************** Blame Report 1.16.4-2.4.1 ******************
> > Empty template pool found from : stoneholm:start_pool
> > The path represented by this is:  data/stoneholm/worldgen/template_pool/start_pool.json
> > Most common cause is that there is a typo in this path to the template pool which then points to a non-existent pool.
> > Please let the mod author know about this so they can double check the path to make sure it is correct.

Yeah that is super weird. If you actually open the jar in like 7zip and go to ``data/stoneholm/worldgen/template_pool/`` can you find ``start_pool.json``?

**Comment by deadspidervenom** [comment]
I can indeed find it

**Comment by TheGrimsey** [comment]
Got no idea why this happens. If this is still an issue reopen this.
