### ISSUE TITLE
Items that can be waterlogged are

### ISSUE THREAD

**Issue by 593shaun** [TheGrimsey/Stoneholm#6]
**Description**
In villages generated in an underwater area (if part of the village extends into a lake/river/ocean), anything that has a waterlogged variant (slabs, stairs, lanterns etc.) will be waterlogged.

**To Reproduce**
1. Generate a new world
2. Find a village that is partially submerged
3. Observe this issue

**Expected behavior**
Regular variants of blocks should generate.

**Mod version:**
1.2.7

**Fabric API version:**
0.36.0

**Minecraft version:**
1.17

**Comment by TheGrimsey** [comment]
Upgrade to 1.3. 

This is one of the things I majorly fixed in that verison. Which did release days before this issue was posted.
