### ISSUE TITLE
Villages partially or fully underwater bug

### ISSUE THREAD

**Issue by PuppetMasterZee** [TheGrimsey/Stoneholm#7]
**Describe the bug**
Villages partially or fully underwater have water source blocks spawning on lanterns and other items.

**To Reproduce**
1. Go to Underground Village partially or fully under water. 
2. Go down the halls where water is dripping from ceiling.
3. Note that water source blocks are on the lanterns, doors, etc (I have seen water source blocks on "tables"  made of slabs and upside down stairs.)  No other water source block in the area.
4.  Occurs in both Single-Player and on Multi-Player servedr

**Expected behavior**

**Mod version:  stoneholm-1.2.3 **

**Fabric API version: fabric-api-0.36.0+1.16 **

**Minecraft version: 1.16.5**

**Screenshots**

![2021-07-10_11 37 59](https://user-images.githubusercontent.com/84147261/125174040-31120b00-e188-11eb-8b7c-b3ee89a39609.png)

![2021-07-10_14 13 08](https://user-images.githubusercontent.com/84147261/125174178-168c6180-e189-11eb-9ed5-5656d504d5e4.png)

**Additional Context:**

**Comment by TheGrimsey** [comment]
>  stoneholm-1.2.3

This issue was majorly fixed in 1.3.

1.16.5 is an older minecraft version and I am no longer supporting it.

**Comment by PuppetMasterZee** [comment]
Thank you.  We appreciate the response.
